### ISSUE TITLE
As a designer research endless runners 

### ISSUE THREAD

**Issue by HeatherBishop** [UoSGamesGroups/first-semester-l4-5-group-3#53]
-Why are they fun?
- What kind of experience do players have whilst playing them?
- What design choices have been made to improve the player experience?

2 hours.

**Comment by HeatherBishop** [comment]
2 hours.

**Comment by HeatherBishop** [comment]
Closed Nathaniels' Issue instead of my own.

**Comment by Nat-Berger** [comment]
[Endless Runner Research.docx](https://github.com/UoSGamesGroups/first-semester-l4-5-group-3/files/604254/Endless.Runner.Research.docx)

2 hours
